# Generated by Django 5.0.3 on 2024-03-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_fotografia_mais_vistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='mais_curtidas',
            field=models.IntegerField(default=0),
        ),
    ]
