# Generated by Django 5.0.3 on 2024-04-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_fotografia_mais_curtidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='surpreenda_me',
            field=models.URLField(blank=True, default='https://picsum.photos/200/300', null=True),
        ),
    ]
