# Generated by Django 5.0.3 on 2024-04-03 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_fotografia_favoritas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='favoritas',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='favoritas',
            field=models.ManyToManyField(blank=True, related_name='fotos_favoritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
